version: '3'

services:
  bot:
    image: bot_image
    build:
      context: .
    container_name: bot
    env_file:
      - .env.docker
    command: /bin/sh -c "alembic upgrade head && python3 main.py"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    ports:
      - '1234:5432'
    env_file:
      - .env.docker
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgresdata:
    driver: local