services:
  db:
    image: postgres
    container_name: db
    ports:
      - ${HOST_PORT}:${PSQL_PORT}
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - psqldata:/var/lib/postgresql/data
    networks:
      - my_network

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - ${RABBITMQ_DEFAULT_PORT}:${RABBITMQ_DEFAULT_PORT}
      - ${WEB_RABBIT_PORT}:${WEB_RABBIT_PORT}
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
      - my_network
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
      - ./nats/config/server.conf:/config/server.conf
    networks:
      - my_network
  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    volumes:
      - nui_data:/db
    depends_on:
      - nats
    networks:
      - my_network

volumes:
  psqldata:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  nats_data:
    driver: local
  nui_data:
    driver: local

networks:
  my_network:
    name: my_network
